### ISSUE TITLE
linuxPanbox

### ISSUE THREAD

**Issue by morvarid123morvarid** [Rohde-Schwarz-Cybersecurity/PanBox#84]
Hello,
I have the same problem, when I run the ./start.sh  I get the following error:

2017-07-16 05:35:57,203 [main] (org.panbox) - Panbox directory for configuration () does not exists, reset to default: /home/ubuntu/.panbox
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:101)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
	at org.panbox.Settings.setPairingAddressAndInterface(Unknown Source)
	at org.panbox.Settings.<init>(Unknown Source)
	at org.panbox.Settings.getInstance(Unknown Source)
	at org.panbox.desktop.common.PanboxClient.<clinit>(Unknown Source)

what is the problem?

**Comment by caschulz88** [comment]
Hi,

our project partner, who runs the domain panbox.org suddenly turned off the domain panbox.org itself. As we are trying to detect the internet network interface (as it might be the best network pairing interface when pairing devices via LAN/WLAN). We are currently working on a fix for the domain and will push it back online as soon as possible.

As a workaround you can add the panbox.org domain to you local hosts file and set the IP 127.0.0.1 to it so that panbox.org will always be resolved as 127.0.0.1 (and the loopback device will be identified as best network pairing devices, but you can change it later on in the settings).

**Comment by morvarid123morvarid** [comment]
thanks, 
I changed the ip as you said, and run the ./start.sh  but again I get this error:

2017-07-16 22:36:53,100 [main] (org.panbox) - Panbox directory for configuration () does not exists, reset to default: /home/ubuntu/.panbox
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
	at org.panbox.desktop.linux.PanboxClient.setGuiLookAndFeel(Unknown Source)
	at org.panbox.desktop.linux.PanboxClient.main(Unknown Source)

This is the first time that I want to use the panbox, if I changed the ip, is it work for me as usual?
and in linux readme file does not point to any thing about installing Dropbox while in windows version of panbox emphasize that dropbox must be installed before starting installation of panbox, 
for linux version of panbox , is it required?

**Comment by morvarid123morvarid** [comment]
These library are installed:



dbus-java-bin     2.8-6  

Python 2.7.13

python-appindicator  12.10.1+17.04.20170215-0ubuntu1  amd64   Python bindings for libappindicator

python-nautilus    1.1-4ubuntu1    amd64    Python binding for Nautilus components

libbluetooth-dev   5.43-0ubuntu1    amd64    Development files for using the BlueZ Linux Bluetooth library

python-notify   0.1.1-4  amd64        Python bindings for libnotify

python-gtk2  2.24.0-5.1ubuntu1   amd64   Python bindings for the GTK+ widget set

python-dbus  1.2.4-1   amd64   simple interprocess messaging system (Python interface)

java version "1.8.0_131"

**Comment by morvarid123morvarid** [comment]
thanks,
I change the ip as you said, and install ecording to the instructions , but I receive 

TrayIcon error  :  error starting Tray script

**Comment by morvarid123morvarid** [comment]
following dependencies are installed:

dbus-java-bin     2.8-6  

Python 2.7.13

python-appindicator  12.10.1+17.04.20170215-0ubuntu1  amd64   Python bindings for libappindicator

python-nautilus    1.1-4ubuntu1    amd64    Python binding for Nautilus components

libbluetooth-dev   5.43-0ubuntu1    amd64    Development files for using the BlueZ Linux Bluetooth library

python-notify   0.1.1-4  amd64        Python bindings for libnotify

python-gtk2  2.24.0-5.1ubuntu1   amd64   Python bindings for the GTK+ widget set

python-dbus  1.2.4-1   amd64   simple interprocess messaging system (Python interface)

java version "1.8.0_131"
